const sidebars = {};

["ds", "tp", "programmation", "langages", "graphes", "algorithmique", "ia", "logique", "concurrence", "revision"].forEach((e) => {
  sidebars[e] = [
    {
      type: "autogenerated",
      dirName: e,
    },
  ];
});
sidebars["ds"].push({
  type: "link",
  href: 'https://fortierq-notes-app-ctedub.streamlit.app',
  label: 'Notes', 
});
sidebars["concurrence"].push({
  type: "link",
  href: 'https://deadlockempire.github.io',
  label: 'The Deadlock Empire', 
});

module.exports = sidebars;
