type SidebarItem =
  | { type: "autogenerated"; dirName: string }
  | { type: "link"; href: string; label: string };

const sidebars: Record<string, SidebarItem[]> = {};

[
  "ds",
  "tp",
  "langages",
  // "graphes",
  // "algorithmique",
  // "ia",
  // "concurrence",
  // "logique",
  "revisions",
].forEach((e) => {
  sidebars[e] = [
    {
      type: "autogenerated",
      dirName: e,
    },
  ];
});
sidebars["langages"].push({
  type: "link",
  href: "https://fortierq.github.io/automates",
  label: "Exercices interactifs sur les automates",
});
sidebars["revisions"].push({
  type: "link",
  href: "https://fortierq.github.io/ocaml-exercices",
  label: "Exercices de programmation OCaml",
});
sidebars["revisions"].push({
  type: "link",
  href: "https://fortierq.github.io/exercices-c",
  label: "Exercices de programmation C",
});

// sidebars["ds"].push({
//   type: "link",
//   href: "https://fortierq-notes-app-ctedub.streamlit.app",
//   label: "Notes",
// });
// sidebars["concurrence"].push({
//   type: "link",
//   href: "https://deadlockempire.github.io",
//   label: "The Deadlock Empire",
// });

// sidebars["revisions"].push({
//   type: "link",
//   href: "https://sql-exercices.github.io/",
//   label: "Exercices SQL",
// });

// sidebars["revisions"].push({
//   type: "link",
//   href: "https://fortierq.github.io/ocaml-exercices",
//   label: "Exercices OCaml",
// });

// sidebars["logique"].push({
//   type: "link",
//   href: "https://fortierq.github.io/deduction-naturelle",
//   label: "Exercices de déduction naturelle",
// });

module.exports = sidebars;
