const sidebars = {};

[
  "ds",
  "tp",
  "langages",
  "graphes",
  "algorithmique",
  "ia",
  "concurrence",
  "logique",
  "revisions",
].forEach((e) => {
  sidebars[e] = [
    {
      type: "autogenerated",
      dirName: e,
    },
  ];
});
sidebars["ds"].push({
  type: "link",
  href: "https://fortierq-notes-app-ctedub.streamlit.app",
  label: "Notes",
});
sidebars["concurrence"].push({
  type: "link",
  href: "https://deadlockempire.github.io",
  label: "The Deadlock Empire",
});

sidebars["revisions"].push({
  type: "link",
  href: "https://sql-exercices.github.io/",
  label: "Exercices SQL",
});

sidebars["revisions"].push({
  type: "link",
  href: "https://fortierq.github.io/ocaml-exercices",
  label: "Exercices OCaml",
});

sidebars["logique"].push({
  type: "link",
  href: "https://fortierq.github.io/dednat",
  label: "Exercices de déduction naturelle",
});

module.exports = sidebars;
